name: Bazel Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test_ubuntu20:
    name: Linux Ubuntu 20.04 build <GCC 9.3.0>
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel/_bazel_runner"
        key: bazel_ubuntu20
    - name: Install Dependencies
      run: |
        sudo apt-get install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    - name: Build
      run: |
        bazelisk build --config=gcc9 ...
    - uses: actions/upload-artifact@v3
      with:
        name: drone-simulation-ubuntu20.04-x86_64
        path: |
          bazel-bin/apps/map_viewer/map_viewer
          bazel-bin/apps/map_viewer/map_viewer.runfiles/*
          !bazel-bin/apps/map_viewer/map_viewer.runfiles/MANIFEST
          bazel-bin/apps/simulation_visualizer/simulation_visualizer
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/*
          !bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/MANIFEST
        if-no-files-found: error

  build_and_test_ubuntu22:
    name: Linux Ubuntu 22.04 build <GCC 11.2.0>
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel/_bazel_runner"
        key: bazel_ubuntu22
    - name: Install Dependencies
      run: |
        sudo apt-get install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    - name: Build
      run: |
        bazelisk build ...
    - uses: actions/upload-artifact@v3
      with:
        name: drone-simulation-ubuntu22.04-x86_64
        path: |
          bazel-bin/apps/map_viewer/map_viewer
          bazel-bin/apps/map_viewer/map_viewer.runfiles/*
          !bazel-bin/apps/map_viewer/map_viewer.runfiles/MANIFEST
          bazel-bin/apps/simulation_visualizer/simulation_visualizer
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/*
          !bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/MANIFEST
        if-no-files-found: error

  build_and_test_windows10:
    name: Windows 10 build <Visual Studio 2019>
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "C:/users/runneradmin/_bazel_runneradmin"
        key: bazel_windows10
    - name: Build
      run: |
        bazelisk build --config=vs2019 ...
    - uses: actions/upload-artifact@v3
      with:
        name: drone-simulation-windows10-x86_64
        path: |
          bazel-bin/apps/map_viewer/map_viewer.exe
          bazel-bin/apps/map_viewer/map_viewer.runfiles/*
          !bazel-bin/apps/map_viewer/map_viewer.runfiles/MANIFEST
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.exe
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/*
          !bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/MANIFEST
        if-no-files-found: error

  build_and_test_windows11:
    name: Windows 11 build <Visual Studio 2022>
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "C:/users/runneradmin/_bazel_runneradmin"
        key: bazel_windows11
    - name: Build
      run: |
        bazelisk build ...
    - uses: actions/upload-artifact@v3
      with:
        name: drone-simulation-windows11-x86_64
        path: |
          bazel-bin/apps/map_viewer/map_viewer.exe
          bazel-bin/apps/map_viewer/map_viewer.runfiles/*
          !bazel-bin/apps/map_viewer/map_viewer.runfiles/MANIFEST
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.exe
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/*
          !bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/MANIFEST
        if-no-files-found: error

  build_and_test_macos11:
    name: macOS 11 build <Apple Clang13>
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/private/var/tmp/_bazel_runner"
        key: bazel_macos11
    - name: Build
      run: |
        export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
        bazel build ...
    - uses: actions/upload-artifact@v3
      with:
        name: drone-simulation-macos11-universal
        path: |
          bazel-bin/apps/map_viewer/map_viewer
          bazel-bin/apps/map_viewer/map_viewer.runfiles/*
          !bazel-bin/apps/map_viewer/map_viewer.runfiles/MANIFEST
          bazel-bin/apps/simulation_visualizer/simulation_visualizer
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/*
          !bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/MANIFEST
        if-no-files-found: error

  build_and_test_macos12:
    name: macOS 12 build <Apple Clang14>
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/private/var/tmp/_bazel_runner"
        key: bazel_macos12
    - name: Build
      run: |
        export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
        bazel build ...
    - uses: actions/upload-artifact@v3
      with:
        name: drone-simulation-macos12-universal
        path: |
          bazel-bin/apps/map_viewer/map_viewer
          bazel-bin/apps/map_viewer/map_viewer.runfiles/*
          !bazel-bin/apps/map_viewer/map_viewer.runfiles/MANIFEST
          bazel-bin/apps/simulation_visualizer/simulation_visualizer
          bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/*
          !bazel-bin/apps/simulation_visualizer/simulation_visualizer.runfiles/MANIFEST
        if-no-files-found: error
