name: Bazel

on:
   push: {}
   pull_request: {}

jobs:
  build_and_test_ubuntu20:
    name: Linux Ubuntu 20.04 build <GCC 9.3.0>
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel_ubuntu20
    - name: Install Dependencies
      run: |
        sudo apt-get install libasound2-dev,mesa-common-dev,libx11-dev,libxrandr-dev,libxi-dev,xorg-dev,libgl1-mesa-dev,libglu1-mesa-dev
    - name: Build
      run: |
        bazelisk build --config=gcc9 ...

  build_and_test_ubuntu22:
    name: Linux Ubuntu 22.04 build <GCC 11.2.0>
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel_ubuntu22
    - name: Install Dependencies
      run: |
        sudo apt-get install libasound2-dev,mesa-common-dev,libx11-dev,libxrandr-dev,libxi-dev,xorg-dev,libgl1-mesa-dev,libglu1-mesa-dev
    - name: Build
      run: |
        bazelisk build --config=gcc11 ...

  build_and_test_windows10:
    name: Windows 10 build <Visual Studio 2019>
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel_windows10
    - name: Build
      run: |
        bazelisk build --config=vs2019 ...

  build_and_test_windows11:
    name: Windows 11 build <Visual Studio 2022>
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel_windows11
    - name: Build
      run: |
        bazelisk build --config=vs2022 ...

  build_and_test_macos11:
    name: macOS 11 build <Apple Clang13>
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel_macos11
    - name: Build
      run: |
        bazelisk build --config=macos ...

  build_and_test_macos12:
    name: macOS 12 build <Apple Clang13>
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel_macos12
    - name: Build
      run: |
        bazelisk build --config=macos ...
